// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertDetails) DeepCopyInto(out *AlertDetails) {
	*out = *in
	if in.LabelSelector != nil {
		in, out := &in.LabelSelector, &out.LabelSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertDetails.
func (in *AlertDetails) DeepCopy() *AlertDetails {
	if in == nil {
		return nil
	}
	out := new(AlertDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageAlert) DeepCopyInto(out *StorageAlert) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageAlert.
func (in *StorageAlert) DeepCopy() *StorageAlert {
	if in == nil {
		return nil
	}
	out := new(StorageAlert)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StorageAlert) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageAlertList) DeepCopyInto(out *StorageAlertList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StorageAlert, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageAlertList.
func (in *StorageAlertList) DeepCopy() *StorageAlertList {
	if in == nil {
		return nil
	}
	out := new(StorageAlertList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StorageAlertList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageAlertSpec) DeepCopyInto(out *StorageAlertSpec) {
	*out = *in
	in.StorageAlert.DeepCopyInto(&out.StorageAlert)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageAlertSpec.
func (in *StorageAlertSpec) DeepCopy() *StorageAlertSpec {
	if in == nil {
		return nil
	}
	out := new(StorageAlertSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageAlertStatus) DeepCopyInto(out *StorageAlertStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageAlertStatus.
func (in *StorageAlertStatus) DeepCopy() *StorageAlertStatus {
	if in == nil {
		return nil
	}
	out := new(StorageAlertStatus)
	in.DeepCopyInto(out)
	return out
}
