apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cephalerts.alert.monstorak.org
spec:
  group: alert.monstorak.org
  names:
    kind: CephAlert
    listKind: CephAlertList
    plural: cephalerts
    singular: cephalert
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            storageAlert:
              properties:
                enabled:
                  type: string
                labelSelector:
                  additionalProperties:
                    type: string
                  type: object
                prometheusNamespace:
                  type: string
              type: object
            storageDashboard:
              properties:
                enabled:
                  type: string
                grafanaNamespace:
                  type: string
                labelSelector:
                  additionalProperties:
                    type: string
                  type: object
              type: object
            storageName:
              type: string
            storageVersion:
              type: string
          type: object
        status:
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
