---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: monstorak
  namespace: storage-monitoring
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: monstorak
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: monstorak
subjects:
- kind: ServiceAccount
  name: monstorak
  namespace: storage-monitoring