---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: storagealerts.alerts.monstorak.org
spec:
  group: alerts.monstorak.org
  names:
    kind: StorageAlerts
    listKind: StorageAlertsList
    plural: storagealerts
    singular: storagealerts
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            storageAlert:
              properties:
                enabled:
                  type: boolean
                labelSelector:
                  additionalProperties:
                    type: string
                  type: object
                prometheusNamespace:
                  type: string
              type: object
            storageDashboard:
              properties:
                enabled:
                  type: boolean
                grafanaNamespace:
                  type: string
                labelSelector:
                  additionalProperties:
                    type: string
                  type: object
              type: object
            storageName:
              type: string
            storageVersion:
              type: string
          type: object
        status:
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: monstorak
  namespace: storage-monitoring
  labels:
     app: monstorak
spec:
  replicas: 2
  selector:
    matchLabels:
      app: monstorak
  template:
    metadata:
      labels:
        app: monstorak
    spec:
      serviceAccountName: monstorak
      nodeSelector:
        beta.kubernetes.io/os: linux
        node-role.kubernetes.io/master: ""
      containers:
      - image: uchapaga/monstorak
        imagePullPolicy: Always
        name: monstorak
        env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "monstorak"
---
