apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: monitoring
spec:
  type: NodePort
  ports:
  - name: metrics
    nodePort: 30600
    port: 9090
    protocol: TCP
  selector:
    prometheus: k8s
