---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: monstorak
  namespace: storage-monitoring
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: monstorak
  namespace: storage-monitoring
subjects:
- kind: ServiceAccount
  name: monstorak
roleRef:
  kind: Role
  name: monstorak
  apiGroup: rbac.authorization.k8s.io
