FROM registry.access.redhat.com/ubi7-dev-preview/ubi-minimal:latest

LABEL maintainer "UmangaChapagain <uchapaga@redhat.com>"
LABEL author "UmangaChapagain <uchapaga@redhat.com>"

ENV LANG=en_US.utf8

COPY monstorak-operator /usr/local/bin/monstorak-operator
USER 10001

ENTRYPOINT [ "/usr/local/bin/monstorak-operator" ]
